export const GET_PRODUCTOS= "GET_PRODUCTOS";
export const SAVE_PRODUCTOS= "SAVE_PRODUCTOS";
export const SEARCH_PRODUCTOS= "SEARCH_PRODUCTOS";
export const ADD_PRODUCT= "ADD_PRODUCT";
export const DELETE_PRODUCT= "DELETE_PRODUCT";
export const DELETE_ALLPRODUCTS= "DELETE_ALLPRODUCTS";

